### ISSUE TITLE
Date issue in the Resume Parser feature

### ISSUE THREAD

**Issue by rushilv20** [salonishah01/WolfTrackPlus#2]
1. Date Recognition: Parsing dates from resumes in different date formats (e.g., MM/YYYY, MMM YYYY, MM-YYYY), and different ways of representing date ranges (e.g., "January 2019 - February 2021" vs. "01/2019 - 02/2021" etc.).

**Comment by rushilv20** [comment]
2. Data Extraction: There is not one standard format for resumes. So extracting information from different kinds of resumes is difficult. Parsing errors are incomplete or incorrect information extraction.

**Comment by sahilchanglani** [comment]
This is working now
